version: '3.8'

services:

  postgres-storage:
    image: postgres:15-alpine
    container_name: postgres-storage
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}       
      POSTGRES_USER: ${POSTGRES_USER}       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: minio-movie-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build: ./fastapi-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-gateway:/app
    environment:
      STORAGE_URL: ${STORAGE_URL}
      
  storage-spring:
    build:
      context: ./springboot-storage             
      dockerfile: Dockerfile     
    container_name: storage-spring-boot
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-storage:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      STORAGE_ENDPOINT: http://minio:9000
      STORAGE_BUCKET: movies
      STORAGE_ACCESS_KEY: ${MINIO_ROOT_USER}
      STORAGE_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    depends_on:
      postgres-storage:
        condition: service_healthy
      minio:
        condition: service_healthy